- hosts: all
  become: true
  vars:
    app_dir: /var/www/html/tp-app
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy application files
      copy:
        src: ./app/
        dest: "{{ app_dir }}"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Deploy Nginx config
      template:
        src: nginx_vhost.conf.j2
        dest: /etc/nginx/sites-available/default

    - name: Reload Nginx
      service:
        name: nginx
        state: restarted
