- hosts: all
  become: true
  vars:
    app_dir: /var/www/html/gtacd
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Create app directory
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy application files recursively
      copy:
        src: /home/deployuser/gtacd/app/
        dest: "{{ app_dir }}"
        owner: www-data
        group: www-data
        mode: '0644'
        remote_src: yes
        directory_mode: '0755'

    - name: Deploy Nginx config
      template:
        src: nginx_vhost.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'

    - name: Deploy Nginx config
      template:
        src: nginx_vhost.conf.j2
        dest: /etc/nginx/sites-available/gtacd
        owner: root
        group: root
        mode: '0644'


    - name: Reload Nginx
      service:
        name: nginx
        state: restarted
    
    - name: Enable default site (if needed)
      file:
        src: /etc/nginx/sites-available/gtacd
        dest: /etc/nginx/sites-enabled/gtacd
        state: link
        force: yes

    - name: List files in app directory to verify deployment
      command: ls -l "{{ app_dir }}"
      register: ls_output

    - debug:
        var: ls_output.stdout_lines
