- name: Deploy Web App
  hosts: all
  become: true

  vars:
    app_path: /var/www/html/tp-app

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Create app directory
      file:
        path: "{{ app_path }}"
        state: directory
        mode: '0755'

    - name: Copy app files
      copy:
        src: ../app/
        dest: "{{ app_path }}"
        mode: '0644'

    - name: Configure Nginx
      template:
        src: nginx_vhost.conf.j2
        dest: /etc/nginx/sites-available/tp-app.conf

    - name: Enable site
      file:
        src: /etc/nginx/sites-available/tp-app.conf
        dest: /etc/nginx/sites-enabled/tp-app.conf
        state: link
        force: true

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
