---
- name: Déployer l'application web
  hosts: all
  become: yes
  vars:
    app_src: "../app"
    app_dest: "/var/www/html/tp-app"

  tasks:
    - name: Installer Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Créer le dossier de destination
      file:
        path: "{{ app_dest }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copier les fichiers de l'application
      copy:
        src: "{{ app_src }}/"
        dest: "{{ app_dest }}/"
        owner: www-data
        group: www-data"
        mode: '0644'

    - name: Redémarrer Nginx
      service:
        name: nginx
        state: restarted
