name: Basic CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run application check script
        run: ./app/check_app.sh

      - name: Display index.html content
        run: cat app/index.html
