name: CI/CD Full

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupération du code
        uses: actions/checkout@v3

      - name: Test fictif (build)
        run: echo "Build/test réussis – prêt à déployer"

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du dépôt
        uses: actions/checkout@v3

      - name: Configuration de la clé SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Vérification des secrets
        run: |
          if [ -z "${{ secrets.VM_IP }}" ]; then
            echo "Erreur : SERVER_IP est vide"
            exit 1
          fi
          if [ -z "${{ secrets.VM_USER }}" ]; then
            echo "Erreur : SERVER_USER est vide"
            exit 1
          fi
          echo "Secrets présents."

      - name: Création du fichier d'inventaire Ansible
        run: |
          PORT=${{ secrets.VM_PORT }}
          if [ -z "$PORT" ]; then
            PORT=22
          fi
          echo "[web]" > ansible/inventory.ini
          echo "${{ secrets.VM_HOST }} ansible_user=${{ secrets.VM_USER }} ansible_port=$PORT ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> ansible/inventory.ini
          chmod 600 ansible/inventory.ini
          echo "Contenu du fichier inventory.ini :"
          cat ansible/inventory.ini

      - name: Installation d'Ansible
        run: |
          sudo apt update && sudo apt install -y python3-pip
          pip3 install ansible

      - name: Lancement du playbook Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
