name: CI/CD Full Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Ajoute ici tes tests s'il y en a

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create inventory file
        run: |
          echo "[web]" > inventory.ini
          echo "${{ secrets.SERVER_IP }} ansible_user=${{ secrets.SERVER_USER }}" >> inventory.ini
          chmod 600 inventory.ini

      - name: Install Ansible
        run: |
          sudo apt update && sudo apt install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/deploy.yml -i inventory.ini
