name: CI/CD Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 2222 -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: |
        rsync -az -e "ssh -p 2222 -i ~/.ssh/id_rsa" --delete ./ \
          ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:/home/${{ secrets.VM_USER }}/gtacd/

    - name: Start app with docker-compose
      run: |
        ssh -p 2222 -i ~/.ssh/id_rsa ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} \
          "cd /home/${{ secrets.VM_USER }}/gtacd && docker-compose up -d --build"
